name: Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          dotnet tool install --global coverlet.console
          coverlet test/Jokenizer.Net.Tests/bin/Release/net9.0/Jokenizer.Net.Tests.dll --target "dotnet" --targetargs "test test/Jokenizer.Net.Tests/Jokenizer.Net.Tests.csproj --no-build -c Release" --format opencover --output opencoverCoverage.xml

      - name: Upload coverage to Codecov
        run: |
          curl -s https://codecov.io/bash > codecov
          bash codecov -f opencoverCoverage.xml -t ${{ secrets.CODECOV_TOKEN }}

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Determine version
        run: echo "VERSION=$(gitversion /showvariable SemVer)" >> $GITHUB_ENV

      - name: Pack NuGet package
        run: dotnet pack src/Jokenizer.Net/Jokenizer.Net.csproj --configuration Release --output ./packages --version $VERSION

      - name: Publish NuGet package (on tag push)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          dotnet nuget push "./packages/Jokenizer.Net.*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source "https://api.nuget.org/v3/index.json" --skip-duplicate
